welcome = "Ласкаво просимо до Tiny-shop!"
welcome_text = """<p>Раді вітати вас на шляху до встановлення <b>Tiny-shop</b>!</p>
<p>Наш інтернет-магазин створений з акцентом на швидкість, безпеку та масштабованість, і він ідеально підходить для великих проєктів.<br>
Він побудований на основі мови програмування Rust, що робить його одним з найшвидших рішень на ринку для інтернет-магазинів. З можливістю обробляти понад 1 мільйон товарів і підтримкою бази даних PostgreSQL 16+, <b>Tiny-shop</b> допоможе вам вивести ваш бізнес на новий рівень.</p>
<p>Магазин підтримує багатомовність, що дозволяє вам обслуговувати клієнтів у різних країнах з максимальним комфортом.</p>
<p><b>Tiny-shop</b> є відкритим проєктом з відкритим вихідним кодом, який можна завантажити з нашого <a href="https://github.com/tryteex/tiny-shop" target="_blank">GitHub</a>-репозиторію. Ми активно підтримуємо проєкт і запрошуємо всіх приєднуватися до спільноти через наш <a href="https://discord.com/channels/1116858532491448332/1116858533061869742" target="_blank"> Discord канал</a>, де ви можете спілкуватися з іншими користувачами та розробниками.</p>
<p>Крім того, ми підтримуємо плагіни і хуки, які дозволяють інтегрувати додаткові функції від сторонніх розробників. Ці модулі можуть бути як безкоштовними, так і платними, що дозволяє розширювати функціональність магазину відповідно до ваших потреб.</p>
<p>Проєкт існує завдяки підтримці нашої спільноти. Якщо вам подобається <b>Tiny-shop</b> і ви хочете сприяти його подальшому розвитку, будь ласка, розгляньте можливість донату.<br>
Ваші внески допоможуть нам підтримувати проєкт, додавати нові функції та покращувати його для всіх користувачів. Ви можете зробити донат через <a href="https://github.com/sponsors/tryteex/" target="_blank">GitHub Sponsors</a>.</p>
<p>Натисніть "Далі", щоб розпочати налаштування вашого магазину!</p>"""
next = "Далі"
license = "Ліцензійна угода!"
license_text = """<p>Перед тим як продовжити процес встановлення <b>Tiny-shop</b>, будь ласка, ознайомтеся з нашими ліцензійними умовами. Проєкт є відкритим програмним забезпеченням (open source) і доступний для завантаження з <a href="https://github.com/tryteex/tiny-shop" target="_blank">GitHub</a>-репозиторію.</p>
<p>Проєкт <b>Tiny-shop</b> поширюється під ліцензією <a href="https://github.com/tryteex/tiny-shop/blob/main/LICENSE" target="_blank">MIT</a> (про ліцензію <a href="https://uk.wikipedia.org/wiki/%D0%9B%D1%96%D1%86%D0%B5%D0%BD%D0%B7%D1%96%D1%8F_MIT" target="_blank">MIT</a>), що дає вам свободу використовувати, модифікувати і розповсюджувати код за умови дотримання умов ліцензії.</p>
</p>Основні умови ліцензії:
    <ul>
    <li>Ви можете вільно використовувати цей код у власних проєктах і модифікувати його під ваші потреби.</li>
    <li>У разі поширення модифікованого коду ви повинні зберегти оригінальні авторські права та умови ліцензії.</li>
    <li>Програмне забезпечення надається "як є", без будь-яких гарантій, тому автори не несуть відповідальності за можливі збитки або втрати, що можуть виникнути в процесі його використання.</li>
    </ul>
</p>
<p>Для продовження встановлення, будь ласка, погодьтеся з умовами ліцензії.</p>
"""
license_agree = "Я погоджуюся з умовами ліцензії"
license_not_accept = "На жаль, ви не прийняли умови ліцензії, тому <b>Tiny-shop</b> неможливо встановити."
not_found = "Сторінка не знайдена"
not_found_text = "Ой! Схоже, ви перейшли за невідомим посиланням. Якщо ви вважаєте, що це проблема, будь ласка, повідомте нам."
go_back_home = "Повернутиля на головну"
home = "Головна"
toggle_dark = "Змініть темний режим"
settings = "Налаштування"
config = "Конфігурація Tiny-shop"
config_save = "Зберегти"
config_lang_title = "Встановлення мов"
config_lang_name = "Мова"
config_lang_actions = "Дії"
config_log_title = "Log файл"
config_log_text = "Шлях до log файлу"
config_db_title = "Конфігурація бази даних"
config_cpu_title = "Конфігурація CPU Async"
config_cpu_text = "Рекомендовано кількість CPU + 2"
cpu_max_auto = "Автоматично"
cpu_max_manual = "Вручну"
config_session_title = "Session ключ"
config_session_text = "Назва ключа session для браузера"
config_salt_title = "Конфігурація salt"
config_salt_text = "Введіть секретний рядок"
config_db_host = "Хост"
config_db_port = "Порт"
config_db_name = "Назва"
config_db_user = "Користувач"
config_db_pwd = "Пароль"
db_ssl = "SSL потрібен"
db_max_text = "Кількість з'єднаннь"
db_max_auto = "Автоматично"
db_max_manual = "Вручну"
config_db_check = "Перевірити"
config_db_checking = "Перевірка ..."
config_db_check_err_server = "Помилка сервера"
config_db_check_timeout = "Час очікування запиту минув"
config_db_check_err_network = "Сталася помилка мережі"
config_db_check_err_answer = "Помилка аналізу відповіді JSON"
config_db_check_err_json = "Невідомий status у відповідь"
config_db_err = "Неправильні параметри запиту"
config_db_ok = "З'єднання успішно встановлено, час на сервері"
config_db_error = "Помилка встановлення з'єднання"
config_db_type = "Тип бази даних"
config_saving = "Перевірка і зберігання ..."
config_err_server = "Помилка сервера"
config_err_network = "Сталася помилка мережі"
config_timeout = "Час очікування запиту минув"
config_err_answer = "Помилка аналізу відповіді JSON"
config_err_json = "Невідомий status у відповідь"
config_save_err = "Неправильні параметри запиту"
config_save_cpu_err = "Помилкове значення в \"Конфігурація CPU Async\". Може бути або \"Автоматично\"  або число"
config_save_log_err = "Помилкове значення в \"Log файл\". Не може бути пустим"
config_save_salt_err = "Помилкове значення в \"Session ключ\". Не може бути пустим"
config_save_session_err = "Помилкове значення в \"Конфігурація salt\". Не може бути пустим"
config_save_lang_err = "Не вибрана жодна мова"
config_save_file_err = "Не вдалося записати файл конфігурації"
config_save_install_sql_err = "Не вдалося отримати sql запит ініціалізації бази даних"
success = "Встановлення успішно завершено!"
success_text = "<p>Вітаємо!</p></p><p>Ви успішно завершили встановлення <b>Tiny-shop</b>.</p><p>Тепер ви можете перейти на головну сторінку та розпочати роботу з вашим сайтом.</p>"
